In [18]:
import pandas as pd
import numpy as np

In [19]:
l1 = pd.read_csv('l1_day.csv')

In [20]:
l1.head()

,ts_recv,ts_event,rtype,publisher_id,instrument_id,action,side,depth,price,size,...,ask_sz_08,bid_ct_08,ask_ct_08,bid_px_09,ask_px_09,bid_sz_09,ask_sz_09,bid_ct_09,ask_ct_09,symbol
0,2024-08-01T13:36:32.492082308Z,2024-08-01T13:36:32.491911683Z,10,2,38,T,A,0,222.81,190,...,100,4,1,222.72,222.94,219,317,3,5,AAPL
1,2024-08-01T13:36:32.492082308Z,2024-08-01T13:36:32.491911683Z,10,2,38,T,A,0,222.81,10,...,100,4,1,222.72,222.94,219,317,3,5,AAPL
2,2024-08-01T13:36:32.492082308Z,2024-08-01T13:36:32.491911683Z,10,2,38,T,A,0,222.81,100,...,100,4,1,222.72,222.94,219,317,3,5,AAPL
3,2024-08-01T13:36:32.492082308Z,2024-08-01T13:36:32.491911683Z,10,2,38,T,A,0,222.81,121,...,100,4,1,222.72,222.94,219,317,3,5,AAPL
4,2024-08-01T13:36:32.492082308Z,2024-08-01T13:36:32.491912675Z,10,2,38,A,N,0,222.83,10,...,100,3,1,222.71,222.94,1163,317,7,5,AAPL

In [21]:
l1.publisher_id.value_counts()

publisher_id
2    59999
Name: count, dtype: int64

In [ ]:
l1.shape

(59999, 74)

In [ ]:
clean_df =l1.drop_duplicates(subset=['ts_event','publisher_id'], keep='first').sort_values(by='ts_event', ascending=True)

clean_df.head()

,ts_recv,ts_event,rtype,publisher_id,instrument_id,action,side,depth,price,size,...,ask_sz_08,bid_ct_08,ask_ct_08,bid_px_09,ask_px_09,bid_sz_09,ask_sz_09,bid_ct_09,ask_ct_09,symbol
0,2024-08-01T13:36:32.492082308Z,2024-08-01T13:36:32.491911683Z,10,2,38,T,A,0,222.81,190,...,100,4,1,222.72,222.94,219,317,3,5,AAPL
4,2024-08-01T13:36:32.492082308Z,2024-08-01T13:36:32.491912675Z,10,2,38,A,N,0,222.83,10,...,100,3,1,222.71,222.94,1163,317,7,5,AAPL
5,2024-08-01T13:36:32.492093947Z,2024-08-01T13:36:32.491927912Z,10,2,38,A,A,0,222.83,100,...,100,3,1,222.71,222.94,1163,317,7,5,AAPL
6,2024-08-01T13:36:32.492105645Z,2024-08-01T13:36:32.491939846Z,10,2,38,A,A,0,222.82,87,...,219,3,3,222.71,222.93,1163,100,7,1,AAPL
7,2024-08-01T13:36:32.492110610Z,2024-08-01T13:36:32.491944432Z,10,2,38,A,B,1,222.79,100,...,219,3,3,222.71,222.93,1163,100,7,1,AAPL

In [ ]:
len(clean_df.publisher_id.unique())

1

In [ ]:
def optimal_order_allocation(df,l,lambda_under, lambda_over, S, Q, theta):
    if len(df.publisher_id.unique()) == 1:
        if l >= lambda_under:

SyntaxError: incomplete input (1806331595.py, line 4)